### ISSUE TITLE
Games not updating locally

### ISSUE THREAD

**Issue by wowbaggerBR** [SilicaAndPina/psvtrophyisgood#11]
Hi, thanks for the awesome tool!

It works perfectly for unlocking and syncing, but I noticed that it didn't update the game locally. It shows the trophies as unlocked, but in the main list of games it still shows as bellow 100%, as if I didn't have unlocked the trophys.

Is there a way to force the Vita trophy app to update the count as it does with the server side?

**Comment by SilicaAndPina** [comment]
yea, i dont understand how the progress bar acturally works. and it syncs without it so i was like "eh good enough"

**Comment by wowbaggerBR** [comment]
Oh, I see. Well, not a problem then =)
