### ISSUE TITLE
Change TimeStamp doesn't working properly.

### ISSUE THREAD

**Issue by 4rchitect** [SilicaAndPina/psvtrophyisgood#3]
Change Timestamp screen doesn't show the last time used properly (Day, Hour, Minute and Second).
It's behaving like this.

* Day value gets the last month value.
* Hour gets last hour -1.
* Minute gets last Minute -1.
* Second gets last Second -1.

Using your binary release for windows v1.1

**Comment by Reiza72** [comment]
Any news? 
Is very HARD to change the TimeStamp properly. I just make a trophy List for my self with every TimeStamp, but when i sink with server some trophy was with "TimeStamp Missing". 
Fix the Tool, or just delete from here.

**Comment by SilicaAndPina** [comment]
fixed i think?
