### ISSUE TITLE
encrypting question/ remove owner

### ISSUE THREAD

**Issue by Thibobo** [SilicaAndPina/psvtrophyisgood#5]
when the process of psvtig is done (decrypting, edit, re-encrypt) is the (encrypted)trophy folder then tied with the user/psnaccount where it's been re-encrypted on?

Because i always need to decrypt the trophy & encrypt again with the same user in order to make it to work, i thought "remove owner" option makes every trophy folder that gets encrypted again works right away on any user, am i wrong?

**Comment by SilicaAndPina** [comment]
the encryption done in vitashell / trophyDumper is not user-specific, instead its game-specific 

trophys embed an account id at *some offset i forgot lol*
if its set to 0000000000 then anyone can use that trophy set .-.

**Comment by Thibobo** [comment]
Strange that i can’t get it working if i am using other account even when using remove owner (that probably sets it to 0000000000).

So you say if i have a encrypted, modified, no owner folder i can use it right away on any user?
I tried it several times with multiple games, but no luck, i have to decrypt the folder again, and encrypt again on the other acc, otherwise it won’t show up in my trophies.

Does having a psn account on your user on the vita make any difference? 

Thanks in advance! ;)

**Comment by SilicaAndPina** [comment]
>Does having a psn account on your user on the vita make any difference?
if you have this, then every time you open the trophy app it will write its Account_ID to the trophy foler . .
